services:
  angular-app:
    build: .
    container_name: angular-app
    working_dir: /angular-app
    ports:
      - "4200:4200"
    volumes:
      - /c/Adev/front-test:/angular-app
    environment:
      - STYLE=scss
